apiVersion: skaffold/v4beta9
kind: Config
requires:
  - path: k8s/deps/install-deps.skaffold.yaml
build:
  artifacts:
    - image: ghcr.io/cit-consulting/cm-crl-generator
      context: docker
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - k8s/install
      - k8s/example
deploy:
  tolerateFailuresUntilDeadline: true
  kubectl:  {}
