---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm-crl-generator
rules:
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates", "certificaterequests", "issuers", "clusterissuers", "certificates/status" ]
    verbs: [ "get", "watch", "list", "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces", "events" ]
    verbs: [ "list", "get" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "list", "watch", "get", "create", "update", "patch", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cm-crl-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cm-crl-generator
subjects:
  - kind: ServiceAccount
    name: cm-crl-generator-controller
    namespace: cert-manager
