apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-2
  namespace: ns-1
spec:
  secretName: cert-2-sec
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 6h
  renewBefore: 1h
  usages:
    - client auth
  subject:
    organizations:
      - citc

  commonName: user2

  issuerRef:
    name: ca-issuer-1
    kind: Issuer
    group: cert-manager.io
